sudo: required
services:
  - docker

before_install:
  - docker build -t kaushikdev/practice-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kaushikdev/practice-docker-react npm run test